export const productsData = [
  {
    id: 1,
    title: "iPhone 14 128GB",
    category: "iphone",
    price: 799,
    imageUrl: "./images/iphone14.png",
  },
  {
    id: 2,
    title: "iPhone 14 Pro 256GB",
    category: "iphone",
    price: 1099,
    imageUrl: "./images/iphone14pro.png",
  },
  {
    id: 3,
    title: "iPhone 14 Pro Max 256GB",
    category: "iphone",
    price: 1199,
    imageUrl: "./images/iphone14promax.png",
  },
  {
    id: 4,
    title: "MacBook Pro M2 2022",
    category: "macbook",
    price: 1299,
    imageUrl: "./images/macbook-pro-m2.webp",
  },
  {
    id: 5,
    title: "MacBook Air M2 2022",
    category: "macbook",
    price: 1199,
    imageUrl: "./images/macbook-air-m2-1.webp",
  },
  {
    id: 6,
    title: "MacBook Pro 14inch M1 2021",
    category: "macbook",
    price: 1999,
    imageUrl: "./images/macbookpro-14-2021.jpeg",
  },
  {
    id: 7,
    title: "Apple Watch Ultra",
    category: "watch",
    price: 799,
    imageUrl: "./images/watch-ultra.jpeg",
  },
  {
    id: 8,
    title: "Apple Watch Series 8",
    category: "watch",
    price: 399,
    imageUrl: "./images/watch-s8.jpeg",
  },
  {
    id: 9,
    title: "Apple Watch SE",
    category: "watch",
    price: 249,
    imageUrl: "./images/watch-se.jpeg",
  },
  {
    id: 10,
    title: "AirPods Pro (2nd generation)",
    category: "airpods",
    price: 249,
    imageUrl: "./images/airpods-pro-2nd.jpeg",
  },
  {
    id: 11,
    title: "AirPods (3rd generation)",
    category: "airpods",
    price: 169,
    imageUrl: "./images/airpods-3rd.jpeg",
  },
  {
    id: 12,
    title: "AirPods (2nd generation)",
    category: "airpods",
    price: 129,
    imageUrl: "./images/airpods-2nd.jpeg",
  },
];
